.Dd July 11, 2025
.Dt PLAKAR-PKG-RM 1
.Os
.Sh NAME
.Nm plakar-pkg-rm
.Nd Uninstall Plakar plugins
.Sh SYNOPSIS
.Nm plakar pkg rm Ar plugin ...
.Sh DESCRIPTION
The
.Nm plakar pkg rm
command removes plugins that have been previously installed with
.Xr plakar-pkg-add 1
command.
.Pp
The list of plugins can be obtained with
.Xr plakar-pkg 1 .
.Sh EXAMPLES
Removing a plugin:
.Bd -literal -offset indent
$ plakar pkg
epic-v1.2.3
$ plakar pkg rm epic-v1.2.3
.Ed
.Sh SEE ALSO
.Xr plakar-pkg 1 ,
.Xr plakar-pkg-add 1
