.Dd July 11, 2025
.Dt PLAKAR-PKG-BUILD 1
.Os
.Sh NAME
.Nm plakar-pkg-build
.Nd Build Plakar plugins from source
.Sh SYNOPSIS
.Nm plakar pkg build Ar recipe.yaml
.Sh DESCRIPTION
The
.Nm plakar pkg build
fetches the sources and builds the plugin as specified in the given
.Xr plakar-pkg-recipe.yaml 5 .
If it builds successfully, the resulting plugin will be created in the
current working directory.
.Sh FILES
.Bl -tag -width Ds
.It Pa ~/.cache/plakar/plugins/
Plugin cache directory.
Respects
.Ev XDG_CACHE_HOME
if set.
.It Pa ~/.local/share/plakar/plugins
Plugin directory.
Respects
.Ev XDG_DATA_HOME
if set.
.El
.Sh SEE ALSO
.Xr plakar-pkg 1 ,
.Xr plakar-pkg-add 1 ,
.Xr plakar-pkg-create 1 ,
.Xr plakar-pkg-rm 1 ,
.Xr plakar-pkg-recipe.yaml 5
