.Dd July 3, 2025
.Dt PLAKAR-INFO 1
.Os
.Sh NAME
.Nm plakar-info
.Nd Display detailed information about internal structures
.Sh SYNOPSIS
.Nm plakar info
.Op Ar snapshot Ns Oo : Ns Ar /path/to/file Oc
.Sh DESCRIPTION
The
.Nm plakar info
command provides detailed information about a Plakar repository,
snapshots and filesystem entries.
The type of information displayed depends on the specified argument.
Without any arguments, display information about the repository.
.Sh EXAMPLES
Show repository information:
.Bd -literal -offset indent
$ plakar info
.Ed
.Pp
Show detailed information for a snapshot:
.Bd -literal -offset indent
$ plakar info abc123
.Ed
.Pp
Show detailed information for a file within a snapshot:
.Bd -literal -offset indent
$ plakar info abcd123:/etc/passwd
.Ed
.Sh DIAGNOSTICS
.Ex -std
.Bl -tag -width Ds
.It 0
Command completed successfully.
.It >0
An error occurred, such as an invalid snapshot or object ID, or a
failure to retrieve the requested data.
.El
.Sh SEE ALSO
.Xr plakar 1 ,
.Xr plakar-backup 1
