// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MyService_Importer_FullMethodName     = "/myservice.MyService/Importer"
	MyService_Exporter_FullMethodName     = "/myservice.MyService/Exporter"
	MyService_Config_FullMethodName       = "/myservice.MyService/Config"
	MyService_ConfigStream_FullMethodName = "/myservice.MyService/ConfigStream"
)

// MyServiceClient is the client API for MyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MyServiceClient interface {
	Importer(ctx context.Context, in *KeyValueMap, opts ...grpc.CallOption) (*Response, error)
	Exporter(ctx context.Context, in *KeyValueMap, opts ...grpc.CallOption) (*Response, error)
	Config(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CLIMessage], error)
	ConfigStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CLIMessage, CLIMessage], error)
}

type myServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMyServiceClient(cc grpc.ClientConnInterface) MyServiceClient {
	return &myServiceClient{cc}
}

func (c *myServiceClient) Importer(ctx context.Context, in *KeyValueMap, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, MyService_Importer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myServiceClient) Exporter(ctx context.Context, in *KeyValueMap, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, MyService_Exporter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myServiceClient) Config(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CLIMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MyService_ServiceDesc.Streams[0], MyService_Config_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConfigRequest, CLIMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MyService_ConfigClient = grpc.ServerStreamingClient[CLIMessage]

func (c *myServiceClient) ConfigStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CLIMessage, CLIMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MyService_ServiceDesc.Streams[1], MyService_ConfigStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CLIMessage, CLIMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MyService_ConfigStreamClient = grpc.BidiStreamingClient[CLIMessage, CLIMessage]

// MyServiceServer is the server API for MyService service.
// All implementations must embed UnimplementedMyServiceServer
// for forward compatibility.
type MyServiceServer interface {
	Importer(context.Context, *KeyValueMap) (*Response, error)
	Exporter(context.Context, *KeyValueMap) (*Response, error)
	Config(*ConfigRequest, grpc.ServerStreamingServer[CLIMessage]) error
	ConfigStream(grpc.BidiStreamingServer[CLIMessage, CLIMessage]) error
	mustEmbedUnimplementedMyServiceServer()
}

// UnimplementedMyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMyServiceServer struct{}

func (UnimplementedMyServiceServer) Importer(context.Context, *KeyValueMap) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Importer not implemented")
}
func (UnimplementedMyServiceServer) Exporter(context.Context, *KeyValueMap) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exporter not implemented")
}
func (UnimplementedMyServiceServer) Config(*ConfigRequest, grpc.ServerStreamingServer[CLIMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Config not implemented")
}
func (UnimplementedMyServiceServer) ConfigStream(grpc.BidiStreamingServer[CLIMessage, CLIMessage]) error {
	return status.Errorf(codes.Unimplemented, "method ConfigStream not implemented")
}
func (UnimplementedMyServiceServer) mustEmbedUnimplementedMyServiceServer() {}
func (UnimplementedMyServiceServer) testEmbeddedByValue()                   {}

// UnsafeMyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyServiceServer will
// result in compilation errors.
type UnsafeMyServiceServer interface {
	mustEmbedUnimplementedMyServiceServer()
}

func RegisterMyServiceServer(s grpc.ServiceRegistrar, srv MyServiceServer) {
	// If the following call pancis, it indicates UnimplementedMyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MyService_ServiceDesc, srv)
}

func _MyService_Importer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValueMap)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).Importer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MyService_Importer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).Importer(ctx, req.(*KeyValueMap))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyService_Exporter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValueMap)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).Exporter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MyService_Exporter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).Exporter(ctx, req.(*KeyValueMap))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyService_Config_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConfigRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MyServiceServer).Config(m, &grpc.GenericServerStream[ConfigRequest, CLIMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MyService_ConfigServer = grpc.ServerStreamingServer[CLIMessage]

func _MyService_ConfigStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MyServiceServer).ConfigStream(&grpc.GenericServerStream[CLIMessage, CLIMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MyService_ConfigStreamServer = grpc.BidiStreamingServer[CLIMessage, CLIMessage]

// MyService_ServiceDesc is the grpc.ServiceDesc for MyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "myservice.MyService",
	HandlerType: (*MyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Importer",
			Handler:    _MyService_Importer_Handler,
		},
		{
			MethodName: "Exporter",
			Handler:    _MyService_Exporter_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Config",
			Handler:       _MyService_Config_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ConfigStream",
			Handler:       _MyService_ConfigStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/service.proto",
}
