.Dd July 3, 2025
.Dt PLAKAR-DESTINATION 1
.Os
.Sh NAME
.Nm plakar-destination
.Nd Manage Plakar restore destination configuration
.Sh SYNOPSIS
.Nm plakar destination
.Op subcommand ...
.Sh DESCRIPTION
The
.Nm plakar destination
command manages the configuration of destinations where Plakar will restore.
.Pp
The configuration consists in a set of named entries, each of them
describing a destination where a restore operation may happen.
.Pp
A destination is defined by at least a location, specifying the exporter
to use, and some exporter-specific parameters.
.Pp
The subcommands are as follows:
.Bl -tag -width Ds
.It Cm add Ar name Ar location Op option=value ...
Create a new destination entry identified by
.Ar name
with the specified
.Ar location
describing the exporter to use.
Additional exporter options can be set by adding
.Ar option=value
parameters.
.It Cm check Ar name
Check wether the exporter for the destination identified by
.Ar name
is properly configured.
.It Cm ls
Display the current destinations configuration.
This is the default if no subcommand is specified.
.It Cm ping Ar name
Try to open the destination identified by
.Ar name
to make sure it is reachable.
.It Cm rm Ar name
Remove the destination identified by
.Ar name
from the configuration.
.It Cm set Ar name Op option=value ...
Set the
.Ar option
to
.Ar value
for the destination identified by
.Ar name .
Multiple option/value pairs can be specified.
.It Cm unset Ar name Op option ...
Remove the
.Ar option
for the destination entry identified by
.Ar name .
.El
.Sh DIAGNOSTICS
.Ex -std
.Sh SEE ALSO
.Xr plakar 1
