.Dd February 27, 2025
.Dt PLAKAR-CONFIG 1
.Os
.Sh NAME
.Nm plakar config
.Nd Display Plakar configuration
.Sh SYNOPSIS
.Nm
.Cm config
.Sh DESCRIPTION
The
.Nm
command displays the configuration of the Plakar software.
.Sh DIAGNOSTICS
.Ex -std
.Sh SEE ALSO
.Xr plakar 1
.Xr plakar-kloset 1
.Xr plakar-remote 1
