.Dd July 8, 2025
.Dt PLAKAR 1
.Os
.Sh NAME
.Nm plakar
.Nd effortless backups
.Sh SYNOPSIS
.Nm
.Op Fl config Ar path
.Op Fl cpu Ar number
.Op Fl keyfile Ar path
.Op Fl no-agent
.Op Fl quiet
.Op Fl trace Ar subsystems
.Op Cm at Ar kloset
.Ar subcommand ...
.Sh DESCRIPTION
.Nm
is a tool to create distributed, versioned backups with compression,
encryption, and data deduplication.
.Pp
By default,
.Nm
operates on the Kloset store at
.Pa ~/.plakar .
This can be changed either by using the
.Cm at
option.
.Pp
The following options are available:
.Bl -tag -width Ds
.It Fl config Ar path
Use the configuration at
.Ar path .
.It Fl cpu Ar number
Limit the number of parallel workers
.Nm
uses to
.Ar number .
By default it's the number of online CPUs.
.It Fl keyfile Ar path
Read the passphrase from the key file at
.Ar path
instead of prompting.
Overrides the
.Ev PLAKAR_PASSPHRASE
environment variable.
.It Fl no-agent
Run without attempting to connect to the agent.
.It Fl quiet
Disable all output except for errors.
.It Fl trace Ar subsystems
Display trace logs.
.Ar subsystems
is a comma-separated series of keywords to enable the trace logs for
different subsystems:
.Cm all , trace , repository , snapshot No and Cm server .
.It Cm at Ar kloset
Operates on the given
.Ar kloset
store.
It could be a path, an URI, or a label in the form
.Dq @ Ns Ar name
to reference a configuration created with
.Xr plakar-store 1 .
.El
.Pp
The following commands are available:
.Pp
.Bl -tag -width maintenance -compact
.It Cm agent
Run the plakar agent and configure scheduled tasks, documented in
.Xr plakar-agent 1 .
.It Cm archive
Create an archive from a Kloset snapshot, documented in
.Xr plakar-archive 1 .
.It Cm backup
Create a new Kloset snapshot, documented in
.Xr plakar-backup 1 .
.It Cm cat
Display file contents from a Kloset snapshot, documented in
.Xr plakar-cat 1 .
.It Cm check
Check data integrity in a Kloset store, documented in
.Xr plakar-check 1 .
.It Cm clone
Clone a Kloset store to a new location, documented in
.Xr plakar-clone 1 .
.It Cm create
Create a new Kloset store, documented in
.Xr plakar-create 1 .
.It Cm destination
Manage configurations for the destination connectors, documented in
.Xr plakar-destination 1 .
.It Cm diff
Show differences between files in a Kloset snapshot, documented in
.Xr plakar-diff 1 .
.It Cm digest
Compute digests for files in a Kloset snapshot, documented in
.Xr plakar-digest 1 .
.It Cm help
Show this manpage and the ones for the subcommands.
.It Cm info
Display detailed information about internal structures, documented in
.Xr plakar-info 1 .
.It Cm locate
Find filenames in a Kloset snapshot, documented in
.Xr plakar-locate 1 .
.It Cm ls
List snapshots and their contents in a Kloset store, documented in
.Xr plakar-ls 1 .
.It Cm maintenance
Remove unused data from a Kloset store, documented in
.Xr plakar-maintenance 1 .
.It Cm mount
Mount Kloset snapshots as a read-only filesystem, documented in
.Xr plakar-mount 1 .
.It Cm ptar
Create a .ptar archive, documented in
.Xr plakar-ptar 1 .
.It Cm pkg
List installed plugins, documented in
.Xr plakar-pkg 1 .
.It Cm pkg add
Install a plugin, documented in
.Xr plakar-pkg-add 1 .
.It Cm pkg build
Build a plugin from source, documented in
.Xr plakar-pkg-build 1 .
.It Cm pkg create
Package a plugin, documented in
.Xr plakar-pkg-create 1 .
.It Cm pkg rm
Unistall a plugin, documented in
.Xr plakar-pkg-rm 1 .
.It Cm restore
Restore files from a Kloset snapshot, documented in
.Xr plakar-restore 1 .
.It Cm rm
Remove snapshots from a Kloset store, documented in
.Xr plakar-rm 1 .
.It Cm server
Start a Plakar server, documented in
.Xr plakar-server 1 .
.It Cm source
Manage configurations for the source connectors, documented in
.Xr plakar-source 1 .
.It Cm store
Manage configurations for storage connectors, documented in
.Xr plakar-store 1 .
.It Cm sync
Synchronize snapshots between Kloset stores, documented in
.Xr plakar-sync 1 .
.It Cm ui
Serve the Plakar web user interface, documented in
.Xr plakar-ui 1 .
.It Cm version
Display the current Plakar version, documented in
.Xr plakar-version 1 .
.El
.Sh ENVIRONMENT
.Bl -tag -width Ds
.It Ev PLAKAR_PASSPHRASE
Passphrase to unlock the Kloset store; overrides the one from the configuration.
If set,
.Nm
won't prompt to unlock.
The option
.Cm keyfile
overrides this environment variable.
.It Ev PLAKAR_REPOSITORY
Reference to the Kloset store.
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa ~/.cache/plakar and Pa ~/.cache/plakar-agentless
Plakar cache directories.
.It Pa ~/.config/plakar/klosets.yml ~/.config/plakar/sources.yml ~/.config/plakar/destinations.yml
Default configuration files.
.It Pa ~/.plakar
Default Kloset store location.
.El
.Sh EXAMPLES
Create an encrypted Kloset store at the default location:
.Bd -literal -offset indent
$ plakar create
.Ed
.Pp
Create an encrypted Kloset store on AWS S3:
.Bd -literal -offset indent
$ plakar store add mys3bucket \\
    location=s3://s3.eu-west-3.amazonaws.com/backups \e
    access_key="access_key" \\
    secret_access_key="secret_key"
$ plakar at @mys3bucket create
.Ed
.Pp
Create a snapshot of the current directory on the @mys3bucket Kloset store:
.Bd -literal -offset indent
$ plakar at @mys3bucket backup
.Ed
.Pp
List the snapshots of the default Kloset store:
.Bd -literal -offset indent
$ plakar ls
.Ed
.Pp
Restore the file
.Dq notes.md
in the current directory from the snapshot with id
.Dq abcd :
.Bd -literal -offset indent
$ plakar restore -to . abcd:notes.md
.Ed
.Pp
Remove snapshots older than 30 days:
.Bd -literal -offset indent
$ plakar rm -before 30d
.Ed
