.Dd February 17, 2025
.Dt PLAKAR-CONFIG 1
.Os
.Sh NAME
.Nm plakar config
.Nd Manages plakar configuration
.Sh SYNOPSIS
.Nm
.Op Ar key Ns Oo = Ns Ar value
.Sh DESCRIPTION
The
.Nm
command manages configuration of the Plakar software.
.Pp
Without arguments show all the configuration options currently set on the repository.
With just
.Ar key ,
show the value defined for that key.
Otherwise, set
.Ar key
to
.Ar value .
.Pp
.Ar key
is of the form
.Sq Ar category Ns . Ns Ar option .
.Sh DIAGNOSTICS
.Ex -std
.Sh SEE ALSO
.Xr plakar 1
