// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: exporter.proto

package exporter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Options struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Maxconcurrency int64                  `protobuf:"varint,1,opt,name=maxconcurrency,proto3" json:"maxconcurrency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_exporter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_exporter_proto_rawDescGZIP(), []int{0}
}

func (x *Options) GetMaxconcurrency() int64 {
	if x != nil {
		return x.Maxconcurrency
	}
	return 0
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *Options               `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	Proto         string                 `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	Config        map[string]string      `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_exporter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_exporter_proto_rawDescGZIP(), []int{1}
}

func (x *InitRequest) GetOptions() *Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *InitRequest) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *InitRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_exporter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_exporter_proto_rawDescGZIP(), []int{2}
}

type RootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootRequest) Reset() {
	*x = RootRequest{}
	mi := &file_exporter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootRequest) ProtoMessage() {}

func (x *RootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootRequest.ProtoReflect.Descriptor instead.
func (*RootRequest) Descriptor() ([]byte, []int) {
	return file_exporter_proto_rawDescGZIP(), []int{3}
}

type RootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootPath      string                 `protobuf:"bytes,1,opt,name=root_path,json=rootPath,proto3" json:"root_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootResponse) Reset() {
	*x = RootResponse{}
	mi := &file_exporter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootResponse) ProtoMessage() {}

func (x *RootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootResponse.ProtoReflect.Descriptor instead.
func (*RootResponse) Descriptor() ([]byte, []int) {
	return file_exporter_proto_rawDescGZIP(), []int{4}
}

func (x *RootResponse) GetRootPath() string {
	if x != nil {
		return x.RootPath
	}
	return ""
}

type CreateDirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pathname      string                 `protobuf:"bytes,1,opt,name=pathname,proto3" json:"pathname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectoryRequest) Reset() {
	*x = CreateDirectoryRequest{}
	mi := &file_exporter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectoryRequest) ProtoMessage() {}

func (x *CreateDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectoryRequest.ProtoReflect.Descriptor instead.
func (*CreateDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_exporter_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDirectoryRequest) GetPathname() string {
	if x != nil {
		return x.Pathname
	}
	return ""
}

type CreateDirectoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectoryResponse) Reset() {
	*x = CreateDirectoryResponse{}
	mi := &file_exporter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectoryResponse) ProtoMessage() {}

func (x *CreateDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectoryResponse.ProtoReflect.Descriptor instead.
func (*CreateDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_exporter_proto_rawDescGZIP(), []int{6}
}

type StoreFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*StoreFileRequest_Header
	//	*StoreFileRequest_Data
	Type          isStoreFileRequest_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreFileRequest) Reset() {
	*x = StoreFileRequest{}
	mi := &file_exporter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreFileRequest) ProtoMessage() {}

func (x *StoreFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreFileRequest.ProtoReflect.Descriptor instead.
func (*StoreFileRequest) Descriptor() ([]byte, []int) {
	return file_exporter_proto_rawDescGZIP(), []int{7}
}

func (x *StoreFileRequest) GetType() isStoreFileRequest_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *StoreFileRequest) GetHeader() *Header {
	if x != nil {
		if x, ok := x.Type.(*StoreFileRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *StoreFileRequest) GetData() *Data {
	if x != nil {
		if x, ok := x.Type.(*StoreFileRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isStoreFileRequest_Type interface {
	isStoreFileRequest_Type()
}

type StoreFileRequest_Header struct {
	Header *Header `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type StoreFileRequest_Data struct {
	Data *Data `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*StoreFileRequest_Header) isStoreFileRequest_Type() {}

func (*StoreFileRequest_Data) isStoreFileRequest_Type() {}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pathname      string                 `protobuf:"bytes,1,opt,name=pathname,proto3" json:"pathname,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_exporter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_exporter_proto_rawDescGZIP(), []int{8}
}

func (x *Header) GetPathname() string {
	if x != nil {
		return x.Pathname
	}
	return ""
}

func (x *Header) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_exporter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_exporter_proto_rawDescGZIP(), []int{9}
}

func (x *Data) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type StoreFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreFileResponse) Reset() {
	*x = StoreFileResponse{}
	mi := &file_exporter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreFileResponse) ProtoMessage() {}

func (x *StoreFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreFileResponse.ProtoReflect.Descriptor instead.
func (*StoreFileResponse) Descriptor() ([]byte, []int) {
	return file_exporter_proto_rawDescGZIP(), []int{10}
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	ModTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	Dev           uint64                 `protobuf:"varint,5,opt,name=dev,proto3" json:"dev,omitempty"`
	Ino           uint64                 `protobuf:"varint,6,opt,name=ino,proto3" json:"ino,omitempty"`
	Uid           uint64                 `protobuf:"varint,7,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint64                 `protobuf:"varint,8,opt,name=gid,proto3" json:"gid,omitempty"`
	Nlink         uint32                 `protobuf:"varint,9,opt,name=nlink,proto3" json:"nlink,omitempty"`
	Username      string                 `protobuf:"bytes,10,opt,name=username,proto3" json:"username,omitempty"`
	Groupname     string                 `protobuf:"bytes,11,opt,name=groupname,proto3" json:"groupname,omitempty"`
	Flags         uint32                 `protobuf:"varint,12,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_exporter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_exporter_proto_rawDescGZIP(), []int{11}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileInfo) GetModTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModTime
	}
	return nil
}

func (x *FileInfo) GetDev() uint64 {
	if x != nil {
		return x.Dev
	}
	return 0
}

func (x *FileInfo) GetIno() uint64 {
	if x != nil {
		return x.Ino
	}
	return 0
}

func (x *FileInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *FileInfo) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *FileInfo) GetNlink() uint32 {
	if x != nil {
		return x.Nlink
	}
	return 0
}

func (x *FileInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FileInfo) GetGroupname() string {
	if x != nil {
		return x.Groupname
	}
	return ""
}

func (x *FileInfo) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type SetPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pathname      string                 `protobuf:"bytes,1,opt,name=pathname,proto3" json:"pathname,omitempty"`
	FileInfo      *FileInfo              `protobuf:"bytes,2,opt,name=file_info,json=fileInfo,proto3" json:"file_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPermissionsRequest) Reset() {
	*x = SetPermissionsRequest{}
	mi := &file_exporter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPermissionsRequest) ProtoMessage() {}

func (x *SetPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPermissionsRequest.ProtoReflect.Descriptor instead.
func (*SetPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_exporter_proto_rawDescGZIP(), []int{12}
}

func (x *SetPermissionsRequest) GetPathname() string {
	if x != nil {
		return x.Pathname
	}
	return ""
}

func (x *SetPermissionsRequest) GetFileInfo() *FileInfo {
	if x != nil {
		return x.FileInfo
	}
	return nil
}

type SetPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPermissionsResponse) Reset() {
	*x = SetPermissionsResponse{}
	mi := &file_exporter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPermissionsResponse) ProtoMessage() {}

func (x *SetPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPermissionsResponse.ProtoReflect.Descriptor instead.
func (*SetPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_exporter_proto_rawDescGZIP(), []int{13}
}

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_exporter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_exporter_proto_rawDescGZIP(), []int{14}
}

type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_exporter_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_exporter_proto_rawDescGZIP(), []int{15}
}

var File_exporter_proto protoreflect.FileDescriptor

const file_exporter_proto_rawDesc = "" +
	"\n" +
	"\x0eexporter.proto\x12\bexporter\x1a\x1fgoogle/protobuf/timestamp.proto\"1\n" +
	"\aOptions\x12&\n" +
	"\x0emaxconcurrency\x18\x01 \x01(\x03R\x0emaxconcurrency\"\xc6\x01\n" +
	"\vInitRequest\x12+\n" +
	"\aoptions\x18\x01 \x01(\v2\x11.exporter.OptionsR\aoptions\x12\x14\n" +
	"\x05proto\x18\x02 \x01(\tR\x05proto\x129\n" +
	"\x06config\x18\x03 \x03(\v2!.exporter.InitRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0e\n" +
	"\fInitResponse\"\r\n" +
	"\vRootRequest\"+\n" +
	"\fRootResponse\x12\x1b\n" +
	"\troot_path\x18\x01 \x01(\tR\brootPath\"4\n" +
	"\x16CreateDirectoryRequest\x12\x1a\n" +
	"\bpathname\x18\x01 \x01(\tR\bpathname\"\x19\n" +
	"\x17CreateDirectoryResponse\"l\n" +
	"\x10StoreFileRequest\x12*\n" +
	"\x06header\x18\x01 \x01(\v2\x10.exporter.HeaderH\x00R\x06header\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x0e.exporter.DataH\x00R\x04dataB\x06\n" +
	"\x04type\"8\n" +
	"\x06Header\x12\x1a\n" +
	"\bpathname\x18\x01 \x01(\tR\bpathname\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\"\x1c\n" +
	"\x04Data\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"\x13\n" +
	"\x11StoreFileResponse\"\xab\x02\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x125\n" +
	"\bmod_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\amodTime\x12\x10\n" +
	"\x03dev\x18\x05 \x01(\x04R\x03dev\x12\x10\n" +
	"\x03ino\x18\x06 \x01(\x04R\x03ino\x12\x10\n" +
	"\x03uid\x18\a \x01(\x04R\x03uid\x12\x10\n" +
	"\x03gid\x18\b \x01(\x04R\x03gid\x12\x14\n" +
	"\x05nlink\x18\t \x01(\rR\x05nlink\x12\x1a\n" +
	"\busername\x18\n" +
	" \x01(\tR\busername\x12\x1c\n" +
	"\tgroupname\x18\v \x01(\tR\tgroupname\x12\x14\n" +
	"\x05flags\x18\f \x01(\rR\x05flags\"d\n" +
	"\x15SetPermissionsRequest\x12\x1a\n" +
	"\bpathname\x18\x01 \x01(\tR\bpathname\x12/\n" +
	"\tfile_info\x18\x02 \x01(\v2\x12.exporter.FileInfoR\bfileInfo\"\x18\n" +
	"\x16SetPermissionsResponse\"\x0e\n" +
	"\fCloseRequest\"\x0f\n" +
	"\rCloseResponse2\xa7\x03\n" +
	"\bExporter\x125\n" +
	"\x04Init\x12\x15.exporter.InitRequest\x1a\x16.exporter.InitResponse\x125\n" +
	"\x04Root\x12\x15.exporter.RootRequest\x1a\x16.exporter.RootResponse\x12V\n" +
	"\x0fCreateDirectory\x12 .exporter.CreateDirectoryRequest\x1a!.exporter.CreateDirectoryResponse\x12F\n" +
	"\tStoreFile\x12\x1a.exporter.StoreFileRequest\x1a\x1b.exporter.StoreFileResponse(\x01\x12S\n" +
	"\x0eSetPermissions\x12\x1f.exporter.SetPermissionsRequest\x1a .exporter.SetPermissionsResponse\x128\n" +
	"\x05Close\x12\x16.exporter.CloseRequest\x1a\x17.exporter.CloseResponseb\x06proto3"

var (
	file_exporter_proto_rawDescOnce sync.Once
	file_exporter_proto_rawDescData []byte
)

func file_exporter_proto_rawDescGZIP() []byte {
	file_exporter_proto_rawDescOnce.Do(func() {
		file_exporter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exporter_proto_rawDesc), len(file_exporter_proto_rawDesc)))
	})
	return file_exporter_proto_rawDescData
}

var file_exporter_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_exporter_proto_goTypes = []any{
	(*Options)(nil),                 // 0: exporter.Options
	(*InitRequest)(nil),             // 1: exporter.InitRequest
	(*InitResponse)(nil),            // 2: exporter.InitResponse
	(*RootRequest)(nil),             // 3: exporter.RootRequest
	(*RootResponse)(nil),            // 4: exporter.RootResponse
	(*CreateDirectoryRequest)(nil),  // 5: exporter.CreateDirectoryRequest
	(*CreateDirectoryResponse)(nil), // 6: exporter.CreateDirectoryResponse
	(*StoreFileRequest)(nil),        // 7: exporter.StoreFileRequest
	(*Header)(nil),                  // 8: exporter.Header
	(*Data)(nil),                    // 9: exporter.Data
	(*StoreFileResponse)(nil),       // 10: exporter.StoreFileResponse
	(*FileInfo)(nil),                // 11: exporter.FileInfo
	(*SetPermissionsRequest)(nil),   // 12: exporter.SetPermissionsRequest
	(*SetPermissionsResponse)(nil),  // 13: exporter.SetPermissionsResponse
	(*CloseRequest)(nil),            // 14: exporter.CloseRequest
	(*CloseResponse)(nil),           // 15: exporter.CloseResponse
	nil,                             // 16: exporter.InitRequest.ConfigEntry
	(*timestamppb.Timestamp)(nil),   // 17: google.protobuf.Timestamp
}
var file_exporter_proto_depIdxs = []int32{
	0,  // 0: exporter.InitRequest.options:type_name -> exporter.Options
	16, // 1: exporter.InitRequest.config:type_name -> exporter.InitRequest.ConfigEntry
	8,  // 2: exporter.StoreFileRequest.header:type_name -> exporter.Header
	9,  // 3: exporter.StoreFileRequest.data:type_name -> exporter.Data
	17, // 4: exporter.FileInfo.mod_time:type_name -> google.protobuf.Timestamp
	11, // 5: exporter.SetPermissionsRequest.file_info:type_name -> exporter.FileInfo
	1,  // 6: exporter.Exporter.Init:input_type -> exporter.InitRequest
	3,  // 7: exporter.Exporter.Root:input_type -> exporter.RootRequest
	5,  // 8: exporter.Exporter.CreateDirectory:input_type -> exporter.CreateDirectoryRequest
	7,  // 9: exporter.Exporter.StoreFile:input_type -> exporter.StoreFileRequest
	12, // 10: exporter.Exporter.SetPermissions:input_type -> exporter.SetPermissionsRequest
	14, // 11: exporter.Exporter.Close:input_type -> exporter.CloseRequest
	2,  // 12: exporter.Exporter.Init:output_type -> exporter.InitResponse
	4,  // 13: exporter.Exporter.Root:output_type -> exporter.RootResponse
	6,  // 14: exporter.Exporter.CreateDirectory:output_type -> exporter.CreateDirectoryResponse
	10, // 15: exporter.Exporter.StoreFile:output_type -> exporter.StoreFileResponse
	13, // 16: exporter.Exporter.SetPermissions:output_type -> exporter.SetPermissionsResponse
	15, // 17: exporter.Exporter.Close:output_type -> exporter.CloseResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_exporter_proto_init() }
func file_exporter_proto_init() {
	if File_exporter_proto != nil {
		return
	}
	file_exporter_proto_msgTypes[7].OneofWrappers = []any{
		(*StoreFileRequest_Header)(nil),
		(*StoreFileRequest_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exporter_proto_rawDesc), len(file_exporter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exporter_proto_goTypes,
		DependencyIndexes: file_exporter_proto_depIdxs,
		MessageInfos:      file_exporter_proto_msgTypes,
	}.Build()
	File_exporter_proto = out.File
	file_exporter_proto_goTypes = nil
	file_exporter_proto_depIdxs = nil
}
