.Dd July 3, 2025
.Dt PLAKAR-CLONE 1
.Os
.Sh NAME
.Nm plakar-clone
.Nd Clone a Plakar repository to a new location
.Sh SYNOPSIS
.Nm plakar clone
.Cm to
.Ar path
.Sh DESCRIPTION
The
.Nm plakar clone
command creates a full clone of an existing Plakar repository,
including all snapshots, packfiles, and repository states, and saves
it at the specified
.Ar path .
.Sh EXAMPLES
Clone a repository to a new location:
.Bd -literal -offset indent
plakar clone to /path/to/new/repository
.Ed
.Sh DIAGNOSTICS
.Ex -std
.Bl -tag -width Ds
.It 0
Command completed successfully.
.It >0
An error occurred, such as failure to access the source repository or
to create the target repository.
.El
.Sh SEE ALSO
.Xr plakar 1 ,
.Xr plakar-create 1
