// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: storage.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MAC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MAC) Reset() {
	*x = MAC{}
	mi := &file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MAC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MAC) ProtoMessage() {}

func (x *MAC) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MAC.ProtoReflect.Descriptor instead.
func (*MAC) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *MAC) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proto         string                 `protobuf:"bytes,1,opt,name=proto,proto3" json:"proto,omitempty"`
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *InitRequest) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *InitRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{2}
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        []byte                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{4}
}

type OpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{5}
}

type OpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        []byte                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{6}
}

func (x *OpenResponse) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{7}
}

type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{8}
}

type GetLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationRequest) Reset() {
	*x = GetLocationRequest{}
	mi := &file_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationRequest) ProtoMessage() {}

func (x *GetLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationRequest.ProtoReflect.Descriptor instead.
func (*GetLocationRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{9}
}

type GetLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationResponse) Reset() {
	*x = GetLocationResponse{}
	mi := &file_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationResponse) ProtoMessage() {}

func (x *GetLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationResponse.ProtoReflect.Descriptor instead.
func (*GetLocationResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{10}
}

func (x *GetLocationResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type GetModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModeRequest) Reset() {
	*x = GetModeRequest{}
	mi := &file_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModeRequest) ProtoMessage() {}

func (x *GetModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModeRequest.ProtoReflect.Descriptor instead.
func (*GetModeRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{11}
}

type GetModeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          int32                  `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModeResponse) Reset() {
	*x = GetModeResponse{}
	mi := &file_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModeResponse) ProtoMessage() {}

func (x *GetModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModeResponse.ProtoReflect.Descriptor instead.
func (*GetModeResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{12}
}

func (x *GetModeResponse) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type GetSizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSizeRequest) Reset() {
	*x = GetSizeRequest{}
	mi := &file_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSizeRequest) ProtoMessage() {}

func (x *GetSizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSizeRequest.ProtoReflect.Descriptor instead.
func (*GetSizeRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{13}
}

type GetSizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSizeResponse) Reset() {
	*x = GetSizeResponse{}
	mi := &file_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSizeResponse) ProtoMessage() {}

func (x *GetSizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSizeResponse.ProtoReflect.Descriptor instead.
func (*GetSizeResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{14}
}

func (x *GetSizeResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetStatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatesRequest) Reset() {
	*x = GetStatesRequest{}
	mi := &file_storage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatesRequest) ProtoMessage() {}

func (x *GetStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatesRequest.ProtoReflect.Descriptor instead.
func (*GetStatesRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{15}
}

type GetStatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Macs          []*MAC                 `protobuf:"bytes,1,rep,name=macs,proto3" json:"macs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatesResponse) Reset() {
	*x = GetStatesResponse{}
	mi := &file_storage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatesResponse) ProtoMessage() {}

func (x *GetStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatesResponse.ProtoReflect.Descriptor instead.
func (*GetStatesResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{16}
}

func (x *GetStatesResponse) GetMacs() []*MAC {
	if x != nil {
		return x.Macs
	}
	return nil
}

type PutStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           *MAC                   `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutStateRequest) Reset() {
	*x = PutStateRequest{}
	mi := &file_storage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutStateRequest) ProtoMessage() {}

func (x *PutStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutStateRequest.ProtoReflect.Descriptor instead.
func (*PutStateRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{17}
}

func (x *PutStateRequest) GetMac() *MAC {
	if x != nil {
		return x.Mac
	}
	return nil
}

func (x *PutStateRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type PutStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  int64                  `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutStateResponse) Reset() {
	*x = PutStateResponse{}
	mi := &file_storage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutStateResponse) ProtoMessage() {}

func (x *PutStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutStateResponse.ProtoReflect.Descriptor instead.
func (*PutStateResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{18}
}

func (x *PutStateResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

type GetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           *MAC                   `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_storage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{19}
}

func (x *GetStateRequest) GetMac() *MAC {
	if x != nil {
		return x.Mac
	}
	return nil
}

type GetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateResponse) Reset() {
	*x = GetStateResponse{}
	mi := &file_storage_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateResponse) ProtoMessage() {}

func (x *GetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateResponse.ProtoReflect.Descriptor instead.
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{20}
}

func (x *GetStateResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type DeleteStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           *MAC                   `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStateRequest) Reset() {
	*x = DeleteStateRequest{}
	mi := &file_storage_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStateRequest) ProtoMessage() {}

func (x *DeleteStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStateRequest.ProtoReflect.Descriptor instead.
func (*DeleteStateRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteStateRequest) GetMac() *MAC {
	if x != nil {
		return x.Mac
	}
	return nil
}

type DeleteStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStateResponse) Reset() {
	*x = DeleteStateResponse{}
	mi := &file_storage_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStateResponse) ProtoMessage() {}

func (x *DeleteStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStateResponse.ProtoReflect.Descriptor instead.
func (*DeleteStateResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{22}
}

type GetPackfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackfilesRequest) Reset() {
	*x = GetPackfilesRequest{}
	mi := &file_storage_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackfilesRequest) ProtoMessage() {}

func (x *GetPackfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackfilesRequest.ProtoReflect.Descriptor instead.
func (*GetPackfilesRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{23}
}

type GetPackfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Macs          []*MAC                 `protobuf:"bytes,1,rep,name=macs,proto3" json:"macs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackfilesResponse) Reset() {
	*x = GetPackfilesResponse{}
	mi := &file_storage_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackfilesResponse) ProtoMessage() {}

func (x *GetPackfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackfilesResponse.ProtoReflect.Descriptor instead.
func (*GetPackfilesResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{24}
}

func (x *GetPackfilesResponse) GetMacs() []*MAC {
	if x != nil {
		return x.Macs
	}
	return nil
}

type PutPackfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           *MAC                   `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutPackfileRequest) Reset() {
	*x = PutPackfileRequest{}
	mi := &file_storage_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutPackfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutPackfileRequest) ProtoMessage() {}

func (x *PutPackfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutPackfileRequest.ProtoReflect.Descriptor instead.
func (*PutPackfileRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{25}
}

func (x *PutPackfileRequest) GetMac() *MAC {
	if x != nil {
		return x.Mac
	}
	return nil
}

func (x *PutPackfileRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type PutPackfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  int64                  `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutPackfileResponse) Reset() {
	*x = PutPackfileResponse{}
	mi := &file_storage_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutPackfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutPackfileResponse) ProtoMessage() {}

func (x *PutPackfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutPackfileResponse.ProtoReflect.Descriptor instead.
func (*PutPackfileResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{26}
}

func (x *PutPackfileResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

type GetPackfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           *MAC                   `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackfileRequest) Reset() {
	*x = GetPackfileRequest{}
	mi := &file_storage_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackfileRequest) ProtoMessage() {}

func (x *GetPackfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackfileRequest.ProtoReflect.Descriptor instead.
func (*GetPackfileRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{27}
}

func (x *GetPackfileRequest) GetMac() *MAC {
	if x != nil {
		return x.Mac
	}
	return nil
}

type GetPackfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackfileResponse) Reset() {
	*x = GetPackfileResponse{}
	mi := &file_storage_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackfileResponse) ProtoMessage() {}

func (x *GetPackfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackfileResponse.ProtoReflect.Descriptor instead.
func (*GetPackfileResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{28}
}

func (x *GetPackfileResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type GetPackfileBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           *MAC                   `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        uint32                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackfileBlobRequest) Reset() {
	*x = GetPackfileBlobRequest{}
	mi := &file_storage_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackfileBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackfileBlobRequest) ProtoMessage() {}

func (x *GetPackfileBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackfileBlobRequest.ProtoReflect.Descriptor instead.
func (*GetPackfileBlobRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{29}
}

func (x *GetPackfileBlobRequest) GetMac() *MAC {
	if x != nil {
		return x.Mac
	}
	return nil
}

func (x *GetPackfileBlobRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetPackfileBlobRequest) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type GetPackfileBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackfileBlobResponse) Reset() {
	*x = GetPackfileBlobResponse{}
	mi := &file_storage_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackfileBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackfileBlobResponse) ProtoMessage() {}

func (x *GetPackfileBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackfileBlobResponse.ProtoReflect.Descriptor instead.
func (*GetPackfileBlobResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{30}
}

func (x *GetPackfileBlobResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type DeletePackfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           *MAC                   `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePackfileRequest) Reset() {
	*x = DeletePackfileRequest{}
	mi := &file_storage_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePackfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePackfileRequest) ProtoMessage() {}

func (x *DeletePackfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePackfileRequest.ProtoReflect.Descriptor instead.
func (*DeletePackfileRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{31}
}

func (x *DeletePackfileRequest) GetMac() *MAC {
	if x != nil {
		return x.Mac
	}
	return nil
}

type DeletePackfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePackfileResponse) Reset() {
	*x = DeletePackfileResponse{}
	mi := &file_storage_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePackfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePackfileResponse) ProtoMessage() {}

func (x *DeletePackfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePackfileResponse.ProtoReflect.Descriptor instead.
func (*DeletePackfileResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{32}
}

type GetLocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocksRequest) Reset() {
	*x = GetLocksRequest{}
	mi := &file_storage_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocksRequest) ProtoMessage() {}

func (x *GetLocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocksRequest.ProtoReflect.Descriptor instead.
func (*GetLocksRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{33}
}

type GetLocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Macs          []*MAC                 `protobuf:"bytes,1,rep,name=macs,proto3" json:"macs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocksResponse) Reset() {
	*x = GetLocksResponse{}
	mi := &file_storage_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocksResponse) ProtoMessage() {}

func (x *GetLocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocksResponse.ProtoReflect.Descriptor instead.
func (*GetLocksResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{34}
}

func (x *GetLocksResponse) GetMacs() []*MAC {
	if x != nil {
		return x.Macs
	}
	return nil
}

type PutLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           *MAC                   `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutLockRequest) Reset() {
	*x = PutLockRequest{}
	mi := &file_storage_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutLockRequest) ProtoMessage() {}

func (x *PutLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutLockRequest.ProtoReflect.Descriptor instead.
func (*PutLockRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{35}
}

func (x *PutLockRequest) GetMac() *MAC {
	if x != nil {
		return x.Mac
	}
	return nil
}

func (x *PutLockRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type PutLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  int64                  `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutLockResponse) Reset() {
	*x = PutLockResponse{}
	mi := &file_storage_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutLockResponse) ProtoMessage() {}

func (x *PutLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutLockResponse.ProtoReflect.Descriptor instead.
func (*PutLockResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{36}
}

func (x *PutLockResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

type GetLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           *MAC                   `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLockRequest) Reset() {
	*x = GetLockRequest{}
	mi := &file_storage_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLockRequest) ProtoMessage() {}

func (x *GetLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLockRequest.ProtoReflect.Descriptor instead.
func (*GetLockRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{37}
}

func (x *GetLockRequest) GetMac() *MAC {
	if x != nil {
		return x.Mac
	}
	return nil
}

type GetLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLockResponse) Reset() {
	*x = GetLockResponse{}
	mi := &file_storage_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLockResponse) ProtoMessage() {}

func (x *GetLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLockResponse.ProtoReflect.Descriptor instead.
func (*GetLockResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{38}
}

func (x *GetLockResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type DeleteLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           *MAC                   `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLockRequest) Reset() {
	*x = DeleteLockRequest{}
	mi := &file_storage_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLockRequest) ProtoMessage() {}

func (x *DeleteLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLockRequest.ProtoReflect.Descriptor instead.
func (*DeleteLockRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{39}
}

func (x *DeleteLockRequest) GetMac() *MAC {
	if x != nil {
		return x.Mac
	}
	return nil
}

type DeleteLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLockResponse) Reset() {
	*x = DeleteLockResponse{}
	mi := &file_storage_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLockResponse) ProtoMessage() {}

func (x *DeleteLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLockResponse.ProtoReflect.Descriptor instead.
func (*DeleteLockResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{40}
}

var File_storage_proto protoreflect.FileDescriptor

const file_storage_proto_rawDesc = "" +
	"\n" +
	"\rstorage.proto\x12\x05store\"\x1b\n" +
	"\x03MAC\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"\x96\x01\n" +
	"\vInitRequest\x12\x14\n" +
	"\x05proto\x18\x01 \x01(\tR\x05proto\x126\n" +
	"\x06config\x18\x02 \x03(\v2\x1e.store.InitRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0e\n" +
	"\fInitResponse\"'\n" +
	"\rCreateRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\fR\x06config\"\x10\n" +
	"\x0eCreateResponse\"\r\n" +
	"\vOpenRequest\"&\n" +
	"\fOpenResponse\x12\x16\n" +
	"\x06config\x18\x01 \x01(\fR\x06config\"\x0e\n" +
	"\fCloseRequest\"\x0f\n" +
	"\rCloseResponse\"\x14\n" +
	"\x12GetLocationRequest\"1\n" +
	"\x13GetLocationResponse\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\"\x10\n" +
	"\x0eGetModeRequest\"%\n" +
	"\x0fGetModeResponse\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\x05R\x04mode\"\x10\n" +
	"\x0eGetSizeRequest\"%\n" +
	"\x0fGetSizeResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\"\x12\n" +
	"\x10GetStatesRequest\"3\n" +
	"\x11GetStatesResponse\x12\x1e\n" +
	"\x04macs\x18\x01 \x03(\v2\n" +
	".store.MACR\x04macs\"E\n" +
	"\x0fPutStateRequest\x12\x1c\n" +
	"\x03mac\x18\x01 \x01(\v2\n" +
	".store.MACR\x03mac\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\fR\x05chunk\"7\n" +
	"\x10PutStateResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x03R\fbytesWritten\"/\n" +
	"\x0fGetStateRequest\x12\x1c\n" +
	"\x03mac\x18\x01 \x01(\v2\n" +
	".store.MACR\x03mac\"(\n" +
	"\x10GetStateResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"2\n" +
	"\x12DeleteStateRequest\x12\x1c\n" +
	"\x03mac\x18\x01 \x01(\v2\n" +
	".store.MACR\x03mac\"\x15\n" +
	"\x13DeleteStateResponse\"\x15\n" +
	"\x13GetPackfilesRequest\"6\n" +
	"\x14GetPackfilesResponse\x12\x1e\n" +
	"\x04macs\x18\x01 \x03(\v2\n" +
	".store.MACR\x04macs\"H\n" +
	"\x12PutPackfileRequest\x12\x1c\n" +
	"\x03mac\x18\x01 \x01(\v2\n" +
	".store.MACR\x03mac\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\fR\x05chunk\":\n" +
	"\x13PutPackfileResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x03R\fbytesWritten\"2\n" +
	"\x12GetPackfileRequest\x12\x1c\n" +
	"\x03mac\x18\x01 \x01(\v2\n" +
	".store.MACR\x03mac\"+\n" +
	"\x13GetPackfileResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"f\n" +
	"\x16GetPackfileBlobRequest\x12\x1c\n" +
	"\x03mac\x18\x01 \x01(\v2\n" +
	".store.MACR\x03mac\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\rR\x06length\"/\n" +
	"\x17GetPackfileBlobResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"5\n" +
	"\x15DeletePackfileRequest\x12\x1c\n" +
	"\x03mac\x18\x01 \x01(\v2\n" +
	".store.MACR\x03mac\"\x18\n" +
	"\x16DeletePackfileResponse\"\x11\n" +
	"\x0fGetLocksRequest\"2\n" +
	"\x10GetLocksResponse\x12\x1e\n" +
	"\x04macs\x18\x01 \x03(\v2\n" +
	".store.MACR\x04macs\"D\n" +
	"\x0ePutLockRequest\x12\x1c\n" +
	"\x03mac\x18\x01 \x01(\v2\n" +
	".store.MACR\x03mac\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\fR\x05chunk\"6\n" +
	"\x0fPutLockResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x03R\fbytesWritten\".\n" +
	"\x0eGetLockRequest\x12\x1c\n" +
	"\x03mac\x18\x01 \x01(\v2\n" +
	".store.MACR\x03mac\"'\n" +
	"\x0fGetLockResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"1\n" +
	"\x11DeleteLockRequest\x12\x1c\n" +
	"\x03mac\x18\x01 \x01(\v2\n" +
	".store.MACR\x03mac\"\x14\n" +
	"\x12DeleteLockResponse2\x86\n" +
	"\n" +
	"\x05Store\x12/\n" +
	"\x04Init\x12\x12.store.InitRequest\x1a\x13.store.InitResponse\x125\n" +
	"\x06Create\x12\x14.store.CreateRequest\x1a\x15.store.CreateResponse\x12/\n" +
	"\x04Open\x12\x12.store.OpenRequest\x1a\x13.store.OpenResponse\x122\n" +
	"\x05Close\x12\x13.store.CloseRequest\x1a\x14.store.CloseResponse\x12D\n" +
	"\vGetLocation\x12\x19.store.GetLocationRequest\x1a\x1a.store.GetLocationResponse\x128\n" +
	"\aGetMode\x12\x15.store.GetModeRequest\x1a\x16.store.GetModeResponse\x128\n" +
	"\aGetSize\x12\x15.store.GetSizeRequest\x1a\x16.store.GetSizeResponse\x12>\n" +
	"\tGetStates\x12\x17.store.GetStatesRequest\x1a\x18.store.GetStatesResponse\x12=\n" +
	"\bPutState\x12\x16.store.PutStateRequest\x1a\x17.store.PutStateResponse(\x01\x12=\n" +
	"\bGetState\x12\x16.store.GetStateRequest\x1a\x17.store.GetStateResponse0\x01\x12D\n" +
	"\vDeleteState\x12\x19.store.DeleteStateRequest\x1a\x1a.store.DeleteStateResponse\x12G\n" +
	"\fGetPackfiles\x12\x1a.store.GetPackfilesRequest\x1a\x1b.store.GetPackfilesResponse\x12F\n" +
	"\vPutPackfile\x12\x19.store.PutPackfileRequest\x1a\x1a.store.PutPackfileResponse(\x01\x12F\n" +
	"\vGetPackfile\x12\x19.store.GetPackfileRequest\x1a\x1a.store.GetPackfileResponse0\x01\x12R\n" +
	"\x0fGetPackfileBlob\x12\x1d.store.GetPackfileBlobRequest\x1a\x1e.store.GetPackfileBlobResponse0\x01\x12M\n" +
	"\x0eDeletePackfile\x12\x1c.store.DeletePackfileRequest\x1a\x1d.store.DeletePackfileResponse\x12;\n" +
	"\bGetLocks\x12\x16.store.GetLocksRequest\x1a\x17.store.GetLocksResponse\x12:\n" +
	"\aPutLock\x12\x15.store.PutLockRequest\x1a\x16.store.PutLockResponse(\x01\x12:\n" +
	"\aGetLock\x12\x15.store.GetLockRequest\x1a\x16.store.GetLockResponse0\x01\x12A\n" +
	"\n" +
	"DeleteLock\x12\x18.store.DeleteLockRequest\x1a\x19.store.DeleteLockResponseb\x06proto3"

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData []byte
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)))
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_storage_proto_goTypes = []any{
	(*MAC)(nil),                     // 0: store.MAC
	(*InitRequest)(nil),             // 1: store.InitRequest
	(*InitResponse)(nil),            // 2: store.InitResponse
	(*CreateRequest)(nil),           // 3: store.CreateRequest
	(*CreateResponse)(nil),          // 4: store.CreateResponse
	(*OpenRequest)(nil),             // 5: store.OpenRequest
	(*OpenResponse)(nil),            // 6: store.OpenResponse
	(*CloseRequest)(nil),            // 7: store.CloseRequest
	(*CloseResponse)(nil),           // 8: store.CloseResponse
	(*GetLocationRequest)(nil),      // 9: store.GetLocationRequest
	(*GetLocationResponse)(nil),     // 10: store.GetLocationResponse
	(*GetModeRequest)(nil),          // 11: store.GetModeRequest
	(*GetModeResponse)(nil),         // 12: store.GetModeResponse
	(*GetSizeRequest)(nil),          // 13: store.GetSizeRequest
	(*GetSizeResponse)(nil),         // 14: store.GetSizeResponse
	(*GetStatesRequest)(nil),        // 15: store.GetStatesRequest
	(*GetStatesResponse)(nil),       // 16: store.GetStatesResponse
	(*PutStateRequest)(nil),         // 17: store.PutStateRequest
	(*PutStateResponse)(nil),        // 18: store.PutStateResponse
	(*GetStateRequest)(nil),         // 19: store.GetStateRequest
	(*GetStateResponse)(nil),        // 20: store.GetStateResponse
	(*DeleteStateRequest)(nil),      // 21: store.DeleteStateRequest
	(*DeleteStateResponse)(nil),     // 22: store.DeleteStateResponse
	(*GetPackfilesRequest)(nil),     // 23: store.GetPackfilesRequest
	(*GetPackfilesResponse)(nil),    // 24: store.GetPackfilesResponse
	(*PutPackfileRequest)(nil),      // 25: store.PutPackfileRequest
	(*PutPackfileResponse)(nil),     // 26: store.PutPackfileResponse
	(*GetPackfileRequest)(nil),      // 27: store.GetPackfileRequest
	(*GetPackfileResponse)(nil),     // 28: store.GetPackfileResponse
	(*GetPackfileBlobRequest)(nil),  // 29: store.GetPackfileBlobRequest
	(*GetPackfileBlobResponse)(nil), // 30: store.GetPackfileBlobResponse
	(*DeletePackfileRequest)(nil),   // 31: store.DeletePackfileRequest
	(*DeletePackfileResponse)(nil),  // 32: store.DeletePackfileResponse
	(*GetLocksRequest)(nil),         // 33: store.GetLocksRequest
	(*GetLocksResponse)(nil),        // 34: store.GetLocksResponse
	(*PutLockRequest)(nil),          // 35: store.PutLockRequest
	(*PutLockResponse)(nil),         // 36: store.PutLockResponse
	(*GetLockRequest)(nil),          // 37: store.GetLockRequest
	(*GetLockResponse)(nil),         // 38: store.GetLockResponse
	(*DeleteLockRequest)(nil),       // 39: store.DeleteLockRequest
	(*DeleteLockResponse)(nil),      // 40: store.DeleteLockResponse
	nil,                             // 41: store.InitRequest.ConfigEntry
}
var file_storage_proto_depIdxs = []int32{
	41, // 0: store.InitRequest.config:type_name -> store.InitRequest.ConfigEntry
	0,  // 1: store.GetStatesResponse.macs:type_name -> store.MAC
	0,  // 2: store.PutStateRequest.mac:type_name -> store.MAC
	0,  // 3: store.GetStateRequest.mac:type_name -> store.MAC
	0,  // 4: store.DeleteStateRequest.mac:type_name -> store.MAC
	0,  // 5: store.GetPackfilesResponse.macs:type_name -> store.MAC
	0,  // 6: store.PutPackfileRequest.mac:type_name -> store.MAC
	0,  // 7: store.GetPackfileRequest.mac:type_name -> store.MAC
	0,  // 8: store.GetPackfileBlobRequest.mac:type_name -> store.MAC
	0,  // 9: store.DeletePackfileRequest.mac:type_name -> store.MAC
	0,  // 10: store.GetLocksResponse.macs:type_name -> store.MAC
	0,  // 11: store.PutLockRequest.mac:type_name -> store.MAC
	0,  // 12: store.GetLockRequest.mac:type_name -> store.MAC
	0,  // 13: store.DeleteLockRequest.mac:type_name -> store.MAC
	1,  // 14: store.Store.Init:input_type -> store.InitRequest
	3,  // 15: store.Store.Create:input_type -> store.CreateRequest
	5,  // 16: store.Store.Open:input_type -> store.OpenRequest
	7,  // 17: store.Store.Close:input_type -> store.CloseRequest
	9,  // 18: store.Store.GetLocation:input_type -> store.GetLocationRequest
	11, // 19: store.Store.GetMode:input_type -> store.GetModeRequest
	13, // 20: store.Store.GetSize:input_type -> store.GetSizeRequest
	15, // 21: store.Store.GetStates:input_type -> store.GetStatesRequest
	17, // 22: store.Store.PutState:input_type -> store.PutStateRequest
	19, // 23: store.Store.GetState:input_type -> store.GetStateRequest
	21, // 24: store.Store.DeleteState:input_type -> store.DeleteStateRequest
	23, // 25: store.Store.GetPackfiles:input_type -> store.GetPackfilesRequest
	25, // 26: store.Store.PutPackfile:input_type -> store.PutPackfileRequest
	27, // 27: store.Store.GetPackfile:input_type -> store.GetPackfileRequest
	29, // 28: store.Store.GetPackfileBlob:input_type -> store.GetPackfileBlobRequest
	31, // 29: store.Store.DeletePackfile:input_type -> store.DeletePackfileRequest
	33, // 30: store.Store.GetLocks:input_type -> store.GetLocksRequest
	35, // 31: store.Store.PutLock:input_type -> store.PutLockRequest
	37, // 32: store.Store.GetLock:input_type -> store.GetLockRequest
	39, // 33: store.Store.DeleteLock:input_type -> store.DeleteLockRequest
	2,  // 34: store.Store.Init:output_type -> store.InitResponse
	4,  // 35: store.Store.Create:output_type -> store.CreateResponse
	6,  // 36: store.Store.Open:output_type -> store.OpenResponse
	8,  // 37: store.Store.Close:output_type -> store.CloseResponse
	10, // 38: store.Store.GetLocation:output_type -> store.GetLocationResponse
	12, // 39: store.Store.GetMode:output_type -> store.GetModeResponse
	14, // 40: store.Store.GetSize:output_type -> store.GetSizeResponse
	16, // 41: store.Store.GetStates:output_type -> store.GetStatesResponse
	18, // 42: store.Store.PutState:output_type -> store.PutStateResponse
	20, // 43: store.Store.GetState:output_type -> store.GetStateResponse
	22, // 44: store.Store.DeleteState:output_type -> store.DeleteStateResponse
	24, // 45: store.Store.GetPackfiles:output_type -> store.GetPackfilesResponse
	26, // 46: store.Store.PutPackfile:output_type -> store.PutPackfileResponse
	28, // 47: store.Store.GetPackfile:output_type -> store.GetPackfileResponse
	30, // 48: store.Store.GetPackfileBlob:output_type -> store.GetPackfileBlobResponse
	32, // 49: store.Store.DeletePackfile:output_type -> store.DeletePackfileResponse
	34, // 50: store.Store.GetLocks:output_type -> store.GetLocksResponse
	36, // 51: store.Store.PutLock:output_type -> store.PutLockResponse
	38, // 52: store.Store.GetLock:output_type -> store.GetLockResponse
	40, // 53: store.Store.DeleteLock:output_type -> store.DeleteLockResponse
	34, // [34:54] is the sub-list for method output_type
	14, // [14:34] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		MessageInfos:      file_storage_proto_msgTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
