.Dd July 3, 2025
.Dt PLAKAR-LOCATE 1
.Os
.Sh NAME
.Nm plakar-locate
.Nd Find filenames in a Plakar snapshot
.Sh SYNOPSIS
.Nm plakar locate
.Op Fl name Ar name
.Op Fl category Ar category
.Op Fl environment Ar environment
.Op Fl perimeter Ar perimeter
.Op Fl job Ar job
.Op Fl tag Ar tag
.Op Fl latest
.Op Fl before Ar date
.Op Fl since Ar date
.Op Fl snapshot Ar snapshotID
.Ar patterns ...
.Sh DESCRIPTION
The
.Nm plakar locate
command search all the snapshots to find file names matching any of
the given
.Ar patterns
and prints the abbreviated snapshot ID and the full path of the
matched files.
Matching works according to the shell globbing rules.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl name Ar string
Only apply command to snapshots that match
.Ar name .
.It Fl category Ar string
Only apply command to snapshots that match
.Ar category .
.It Fl environment Ar string
Only apply command to snapshots that match
.Ar environment .
.It Fl perimeter Ar string
Only apply command to snapshots that match
.Ar perimeter .
.It Fl job Ar string
Only apply command to snapshots that match
.Ar job .
.It Fl tag Ar string
Only apply command to snapshots that match
.Ar tag .
.It Fl latest
Only apply command to latest snapshot matching filters.
.It Fl before Ar date
Only apply command to snapshots matching filters and older than the specified
date.
Accepted formats include relative durations
.Pq e.g. "2d" for two days, "1w" for one week
or specific dates in various formats
.Pq e.g. "2006-01-02 15:04:05" .
.It Fl since Ar date
Only apply command to snapshots matching filters and created since the specified
date, included.
Accepted formats include relative durations
.Pq e.g. "2d" for two days, "1w" for one week
or specific dates in various formats
.Pq e.g. "2006-01-02 15:04:05" .
.It Fl snapshot Ar snapshotID
Limit the search to the given snapshot.
.El
.Sh EXAMPLES
Search for files ending in
.Dq wd :
.Bd -literal -offset indent
$ plakar locate '*wd'
abc123:/etc/master.passwd
abc123:/etc/passwd
.Ed
.Sh DIAGNOSTICS
.Ex -std
.Bl -tag -width Ds
.It 0
Command completed successfully.
.It >0
An error occurred, such as invalid parameters, inability to create the
repository, or configuration issues.
.El
.Sh SEE ALSO
.Xr plakar 1 ,
.Xr plakar-backup 1
.Sh CAVEATS
The patterns may have to be quoted to avoid the shell attempting to
expand them.
