.Dd July 3, 2025
.Dt PLAKAR-AGENT 1
.Os
.Sh NAME
.Nm plakar-agent
.Nd Run the Plakar agent
.Sh SYNOPSIS
.Nm plakar agent
.Op Fl foreground
.Op Fl log Ar filename
.Op Cm stop
.Sh DESCRIPTION
The
.Nm plakar agent
command starts the Plakar agent which will execute subsequent
.Xr plakar 1
commands on their behalfs for faster processing.
.Nm plakar agent
continues running indefinitely.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl foreground
Do not daemonize agent,
run in foreground.
.It Fl log Ar filename
Redirect all output to
.Ar filename .
.El
.Pp
With the
.Cm stop
argument,
.Nm plakar agent
will be stopped.
.Sh DIAGNOSTICS
.Ex -std
.Bl -tag -width Ds
.It 0
Command completed successfully.
.It >0
An error occurred, such as invalid parameters, inability to create the
repository, or configuration issues.
.El
.Sh SEE ALSO
.Xr plakar 1
