.Dd July 3, 2025
.Dt PLAKAR-DIAG 1
.Os
.Sh NAME
.Nm plakar-diag
.Nd Display detailed information about Plakar internal structures
.Sh SYNOPSIS
.Nm plakar diag
.Op Cm contenttype | errors | locks | object | packfile | snapshot | state | vfs | xattr
.Sh DESCRIPTION
The
.Nm plakar diag
command provides detailed information about various internal data structures.
The type of information displayed depends on the specified argument.
Without any arguments, display information about the repository.
.Pp
The sub-commands are as follows:
.Bl -tag -width Ds
.It Cm contenttype Ar snapshotID : Ns Ar path
.It Cm errors Ar snapshotID
Display the list of errors in the given snapshot.
.It Cm locks
Display the list of locks currently held on the repository.
.It Cm object Ar objectID
Display information about a specific object, including its mac,
type, tags, and associated data chunks.
.It Cm packfile Ar packfileID
Show details of packfiles, including entries and macs, which
store object data within the repository.
.It Cm snapshot Ar snapshotID
Show detailed information about a specific snapshot, including its
metadata, directory and file count, and size.
.It Cm state
List or describe the states in the repository.
.It Cm vfs Ar snapshotID : Ns Ar path
Show filesystem (VFS) details for a specific path within a snapshot,
listing directory or file attributes, including permissions,
ownership, and custom metadata.
.It Cm xattr Ar snapshotID : Ns Ar path
.El
.Sh EXAMPLES
Show repository information:
.Bd -literal -offset indent
$ plakar diag
.Ed
.Pp
Show detailed information for a snapshot:
.Bd -literal -offset indent
$ plakar diag snapshot abc123
.Ed
.Pp
List all states in the repository:
.Bd -literal -offset indent
$ plakar diag state
.Ed
.Pp
Display a specific object within a snapshot:
.Bd -literal -offset indent
$ plakar diag object 1234567890abcdef
.Ed
.Pp
Display filesystem details for a path within a snapshot:
.Bd -literal -offset indent
$ plakar diag vfs abc123:/etc/passwd
.Ed
.Sh DIAGNOSTICS
.Ex -std
.Bl -tag -width Ds
.It 0
Command completed successfully.
.It >0
An error occurred, such as an invalid snapshot or object ID, or a
failure to retrieve the requested data.
.El
.Sh SEE ALSO
.Xr plakar 1 ,
.Xr plakar-backup 1
