.Dd July 3, 2025
.Dt PLAKAR-CHECK 1
.Os
.Sh NAME
.Nm plakar-check
.Nd Check data integrity in a Plakar repository
.Sh SYNOPSIS
.Nm plakar check
.Op Fl concurrency Ar number
.Op Fl name Ar name
.Op Fl category Ar category
.Op Fl environment Ar environment
.Op Fl perimeter Ar perimeter
.Op Fl job Ar job
.Op Fl tag Ar tag
.Op Fl latest
.Op Fl before Ar date
.Op Fl since Ar date
.Op Fl fast
.Op Fl no-verify
.Op Fl quiet
.Op Ar snapshotID : Ns Ar path ...
.Sh DESCRIPTION
The
.Nm plakar check
command verifies the integrity of data in a Plakar repository.
It checks the given paths inside the snapshots for consistency and
validates file macs to ensure no corruption has occurred, or all
the data in the repository if no
.Ar snapshotID
is given.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl name Ar string
Only apply command to snapshots that match
.Ar name .
.It Fl category Ar string
Only apply command to snapshots that match
.Ar category .
.It Fl environment Ar string
Only apply command to snapshots that match
.Ar environment .
.It Fl perimeter Ar string
Only apply command to snapshots that match
.Ar perimeter .
.It Fl job Ar string
Only apply command to snapshots that match
.Ar job .
.It Fl tag Ar string
Only apply command to snapshots that match
.Ar tag .
.It Fl latest
Only apply command to latest snapshot matching filters.
.It Fl before Ar date
Only apply command to snapshots matching filters and older than the specified
date.
Accepted formats include relative durations
.Pq e.g. "2d" for two days, "1w" for one week
or specific dates in various formats
.Pq e.g. "2006-01-02 15:04:05" .
.It Fl since Ar date
Only apply command to snapshots matching filters and created since the specified
date, included.
Accepted formats include relative durations
.Pq e.g. "2d" for two days, "1w" for one week
or specific dates in various formats
.Pq e.g. "2006-01-02 15:04:05" .
.It Fl concurrency Ar number
Set the maximum number of parallel tasks for faster processing.
Defaults to
.Dv 8 * CPU count + 1 .
.It Fl fast
Enable a faster check that skips mac verification.
This option performs only structural validation without confirming
data integrity.
.It Fl no-verify
Disable signature verification.
This option allows to proceed with checking snapshot integrity
regardless of an invalid snapshot signature.
.It Fl quiet
Suppress output to standard output, only logging errors and warnings.
.El
.Sh EXAMPLES
Perform a full integrity check on all snapshots:
.Bd -literal -offset indent
$ plakar check
.Ed
.Pp
Perform a fast check on specific paths of two snapshot:
.Bd -literal -offset indent
$ plakar check -fast abc123:/etc/passwd def456:/var/www
.Ed
.Sh DIAGNOSTICS
.Ex -std
.Bl -tag -width Ds
.It 0
Command completed successfully with no integrity issues found.
.It >0
An error occurred, such as corruption detected in a snapshot or
failure to check data integrity.
.El
.Sh SEE ALSO
.Xr plakar 1
