.Dd July 3, 2025
.Dt PLAKAR-DIGEST 1
.Os
.Sh NAME
.Nm plakar-digest
.Nd Compute digests for files in a Plakar snapshot
.Sh SYNOPSIS
.Nm plakar digest
.Op Fl hashing Ar algorithm
.Ar snapshotID Ns Op : Ns Ar path
.Op ...
.Sh DESCRIPTION
The
.Nm plakar digest
command computes and displays digests for specified
.Ar path
in a the given
.Ar snapshotID .
Multiple
.Ar snapshotID
and
.Ar path
may be given.
By default, the command computes the digest by reading the file
contents.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl hashing Ar algorithm
Use
.Ar algorithm
to compute the digest.
Defaults to SHA256.
.El
.Sh EXAMPLES
Compute the digest of a file within a snapshot:
.Bd -literal -offset indent
$ plakar digest abc123:/etc/passwd
.Ed
.Pp
Use BLAKE3 as the digest algorithm:
.Bd -literal -offset indent
$ plakar digest -hashing BLAKE3 abc123:/etc/netstart
.Ed
.Sh DIAGNOSTICS
.Ex -std
.Bl -tag -width Ds
.It 0
Command completed successfully.
.It >0
An error occurred, such as failure to retrieve a file digest or
invalid snapshot ID.
.El
.Sh SEE ALSO
.Xr plakar 1
