.Dd July 3, 2025
.Dt PLAKAR-BACKUP 1
.Os
.Sh NAME
.Nm plakar-backup
.Nd Create a new snapshot in a Kloset store
.Sh SYNOPSIS
.Nm plakar backup
.Op Fl concurrency Ar number
.Op Fl exclude Ar pattern
.Op Fl exclude-file Ar file
.Op Fl check
.Op Fl o Ar option
.Op Fl quiet
.Op Fl silent
.Op Fl tag Ar tag
.Op Fl scan
.Op Ar place
.Sh DESCRIPTION
The
.Nm plakar backup
command creates a new snapshot of
.Ar place ,
or the current directory.
Snapshots can be filtered to exclude specific files or directories
based on patterns provided through options.
.Pp
.Ar place
can be either a path, an URI, or a label with the form
.Dq @ Ns Ar name
to reference the source of an integration configured with
.Xr plakar-source 1 .
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl concurrency Ar number
Set the maximum number of parallel tasks for faster processing.
Defaults to
.Dv 8 * CPU count + 1 .
.It Fl exclude Ar pattern
Specify individual glob exclusion patterns to ignore files or
directories in the backup.
This option can be repeated.
.It Fl exclude-file Ar file
Specify a file containing glob exclusion patterns, one per line, to
ignore files or directories in the backup.
.It Fl check
Perform a full check on the backup after success.
.It Fl o Ar option
Can be used to pass extra arguments to the source of the integration.
The given
.Ar option
takes precedence over the configuration file.
.It Fl quiet
Suppress output to standard input, only logging errors and warnings.
.It Fl silent
Suppress all output.
.It Fl tag Ar tag
Specify a tag to assign to the snapshot for easier identification.
.It Fl scan
Do not write a snapshot; instead, perform a dry run by outputting the list of
files and directories that would be included in the backup.
Respects all exclude patterns and other options, but makes no changes to the
Kloset store.
.El
.Sh EXAMPLES
Create a snapshot of the current directory with a tag:
.Bd -literal -offset indent
$ plakar backup -tag daily-backup
.Ed
.Pp
Backup a specific directory with exclusion patterns from a file:
.Bd -literal -offset indent
$ plakar backup -exclude-file ~/my-excludes-file /var/www
.Ed
.Pp
Backup a directory with specific file exclusions:
.Bd -literal -offset indent
$ plakar backup -exclude "*.tmp" -exclude "*.log" /var/www
.Ed
.Sh DIAGNOSTICS
.Ex -std
.Bl -tag -width Ds
.It 0
Command completed successfully; a snapshot was created, but some items may have
been skipped (for example, files without sufficient permissions).
Run
.Xr plakar-info 1
on the new snapshot to view any errors.
.It >0
An error occurred, such as failure to access the Kloset store or issues
with exclusion patterns.
.El
.Sh SEE ALSO
.Xr plakar 1 ,
.Xr plakar-source 1
