// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: importer.proto

package importer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtendedAttributeType int32

const (
	ExtendedAttributeType_EXTENDED_ATTRIBUTE_TYPE_UNSPECIFIED ExtendedAttributeType = 0
	ExtendedAttributeType_EXTENDED_ATTRIBUTE_TYPE_EXTENDED    ExtendedAttributeType = 1
	ExtendedAttributeType_EXTENDED_ATTRIBUTE_TYPE_ADS         ExtendedAttributeType = 2
)

// Enum value maps for ExtendedAttributeType.
var (
	ExtendedAttributeType_name = map[int32]string{
		0: "EXTENDED_ATTRIBUTE_TYPE_UNSPECIFIED",
		1: "EXTENDED_ATTRIBUTE_TYPE_EXTENDED",
		2: "EXTENDED_ATTRIBUTE_TYPE_ADS",
	}
	ExtendedAttributeType_value = map[string]int32{
		"EXTENDED_ATTRIBUTE_TYPE_UNSPECIFIED": 0,
		"EXTENDED_ATTRIBUTE_TYPE_EXTENDED":    1,
		"EXTENDED_ATTRIBUTE_TYPE_ADS":         2,
	}
)

func (x ExtendedAttributeType) Enum() *ExtendedAttributeType {
	p := new(ExtendedAttributeType)
	*p = x
	return p
}

func (x ExtendedAttributeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExtendedAttributeType) Descriptor() protoreflect.EnumDescriptor {
	return file_importer_proto_enumTypes[0].Descriptor()
}

func (ExtendedAttributeType) Type() protoreflect.EnumType {
	return &file_importer_proto_enumTypes[0]
}

func (x ExtendedAttributeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExtendedAttributeType.Descriptor instead.
func (ExtendedAttributeType) EnumDescriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{0}
}

type Options struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Hostname       string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os             string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch           string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Cwd            string                 `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Maxconcurrency int64                  `protobuf:"varint,5,opt,name=maxconcurrency,proto3" json:"maxconcurrency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_importer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{0}
}

func (x *Options) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Options) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Options) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Options) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *Options) GetMaxconcurrency() int64 {
	if x != nil {
		return x.Maxconcurrency
	}
	return 0
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *Options               `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	Proto         string                 `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	Config        map[string]string      `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_importer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{1}
}

func (x *InitRequest) GetOptions() *Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *InitRequest) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *InitRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_importer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{2}
}

func (x *InitResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_importer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{3}
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Origin        string                 `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Root          string                 `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_importer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{4}
}

func (x *InfoResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InfoResponse) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *InfoResponse) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_importer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{5}
}

type ScanResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Pathname string                 `protobuf:"bytes,1,opt,name=pathname,proto3" json:"pathname,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*ScanResponse_Error
	//	*ScanResponse_Record
	Result        isScanResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_importer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{6}
}

func (x *ScanResponse) GetPathname() string {
	if x != nil {
		return x.Pathname
	}
	return ""
}

func (x *ScanResponse) GetResult() isScanResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ScanResponse) GetError() *ScanError {
	if x != nil {
		if x, ok := x.Result.(*ScanResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ScanResponse) GetRecord() *ScanRecord {
	if x != nil {
		if x, ok := x.Result.(*ScanResponse_Record); ok {
			return x.Record
		}
	}
	return nil
}

type isScanResponse_Result interface {
	isScanResponse_Result()
}

type ScanResponse_Error struct {
	Error *ScanError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type ScanResponse_Record struct {
	Record *ScanRecord `protobuf:"bytes,2,opt,name=record,proto3,oneof"`
}

func (*ScanResponse_Error) isScanResponse_Result() {}

func (*ScanResponse_Record) isScanResponse_Result() {}

type ScanError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanError) Reset() {
	*x = ScanError{}
	mi := &file_importer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanError) ProtoMessage() {}

func (x *ScanError) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanError.ProtoReflect.Descriptor instead.
func (*ScanError) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{7}
}

func (x *ScanError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ScanRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Target         string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Fileinfo       *ScanRecordFileInfo    `protobuf:"bytes,2,opt,name=fileinfo,proto3" json:"fileinfo,omitempty"`
	FileAttributes uint32                 `protobuf:"varint,3,opt,name=file_attributes,json=fileAttributes,proto3" json:"file_attributes,omitempty"`
	Xattr          *ExtendedAttribute     `protobuf:"bytes,4,opt,name=xattr,proto3,oneof" json:"xattr,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScanRecord) Reset() {
	*x = ScanRecord{}
	mi := &file_importer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRecord) ProtoMessage() {}

func (x *ScanRecord) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRecord.ProtoReflect.Descriptor instead.
func (*ScanRecord) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{8}
}

func (x *ScanRecord) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ScanRecord) GetFileinfo() *ScanRecordFileInfo {
	if x != nil {
		return x.Fileinfo
	}
	return nil
}

func (x *ScanRecord) GetFileAttributes() uint32 {
	if x != nil {
		return x.FileAttributes
	}
	return 0
}

func (x *ScanRecord) GetXattr() *ExtendedAttribute {
	if x != nil {
		return x.Xattr
	}
	return nil
}

type EOFResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EOFResponse) Reset() {
	*x = EOFResponse{}
	mi := &file_importer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EOFResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EOFResponse) ProtoMessage() {}

func (x *EOFResponse) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EOFResponse.ProtoReflect.Descriptor instead.
func (*EOFResponse) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{9}
}

type ExtendedAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          ExtendedAttributeType  `protobuf:"varint,2,opt,name=type,proto3,enum=importer.ExtendedAttributeType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendedAttribute) Reset() {
	*x = ExtendedAttribute{}
	mi := &file_importer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendedAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendedAttribute) ProtoMessage() {}

func (x *ExtendedAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendedAttribute.ProtoReflect.Descriptor instead.
func (*ExtendedAttribute) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{10}
}

func (x *ExtendedAttribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExtendedAttribute) GetType() ExtendedAttributeType {
	if x != nil {
		return x.Type
	}
	return ExtendedAttributeType_EXTENDED_ATTRIBUTE_TYPE_UNSPECIFIED
}

type ScanRecordFileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	ModTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	Dev           uint64                 `protobuf:"varint,5,opt,name=dev,proto3" json:"dev,omitempty"`
	Ino           uint64                 `protobuf:"varint,6,opt,name=ino,proto3" json:"ino,omitempty"`
	Uid           uint64                 `protobuf:"varint,7,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint64                 `protobuf:"varint,8,opt,name=gid,proto3" json:"gid,omitempty"`
	Nlink         uint32                 `protobuf:"varint,9,opt,name=nlink,proto3" json:"nlink,omitempty"`
	Username      string                 `protobuf:"bytes,10,opt,name=username,proto3" json:"username,omitempty"`
	Groupname     string                 `protobuf:"bytes,11,opt,name=groupname,proto3" json:"groupname,omitempty"`
	Flags         uint32                 `protobuf:"varint,12,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRecordFileInfo) Reset() {
	*x = ScanRecordFileInfo{}
	mi := &file_importer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRecordFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRecordFileInfo) ProtoMessage() {}

func (x *ScanRecordFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRecordFileInfo.ProtoReflect.Descriptor instead.
func (*ScanRecordFileInfo) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{11}
}

func (x *ScanRecordFileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScanRecordFileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ScanRecordFileInfo) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *ScanRecordFileInfo) GetModTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModTime
	}
	return nil
}

func (x *ScanRecordFileInfo) GetDev() uint64 {
	if x != nil {
		return x.Dev
	}
	return 0
}

func (x *ScanRecordFileInfo) GetIno() uint64 {
	if x != nil {
		return x.Ino
	}
	return 0
}

func (x *ScanRecordFileInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ScanRecordFileInfo) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *ScanRecordFileInfo) GetNlink() uint32 {
	if x != nil {
		return x.Nlink
	}
	return 0
}

func (x *ScanRecordFileInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ScanRecordFileInfo) GetGroupname() string {
	if x != nil {
		return x.Groupname
	}
	return ""
}

func (x *ScanRecordFileInfo) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type ScanResponseError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponseError) Reset() {
	*x = ScanResponseError{}
	mi := &file_importer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponseError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponseError) ProtoMessage() {}

func (x *ScanResponseError) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponseError.ProtoReflect.Descriptor instead.
func (*ScanResponseError) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{12}
}

func (x *ScanResponseError) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScanResponseError) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type OpenReaderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pathname      string                 `protobuf:"bytes,1,opt,name=pathname,proto3" json:"pathname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenReaderRequest) Reset() {
	*x = OpenReaderRequest{}
	mi := &file_importer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenReaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenReaderRequest) ProtoMessage() {}

func (x *OpenReaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenReaderRequest.ProtoReflect.Descriptor instead.
func (*OpenReaderRequest) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{13}
}

func (x *OpenReaderRequest) GetPathname() string {
	if x != nil {
		return x.Pathname
	}
	return ""
}

type OpenReaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenReaderResponse) Reset() {
	*x = OpenReaderResponse{}
	mi := &file_importer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenReaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenReaderResponse) ProtoMessage() {}

func (x *OpenReaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenReaderResponse.ProtoReflect.Descriptor instead.
func (*OpenReaderResponse) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{14}
}

func (x *OpenReaderResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type CloseReaderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pathname      string                 `protobuf:"bytes,1,opt,name=pathname,proto3" json:"pathname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseReaderRequest) Reset() {
	*x = CloseReaderRequest{}
	mi := &file_importer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseReaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseReaderRequest) ProtoMessage() {}

func (x *CloseReaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseReaderRequest.ProtoReflect.Descriptor instead.
func (*CloseReaderRequest) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{15}
}

func (x *CloseReaderRequest) GetPathname() string {
	if x != nil {
		return x.Pathname
	}
	return ""
}

type CloseReaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseReaderResponse) Reset() {
	*x = CloseReaderResponse{}
	mi := &file_importer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseReaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseReaderResponse) ProtoMessage() {}

func (x *CloseReaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseReaderResponse.ProtoReflect.Descriptor instead.
func (*CloseReaderResponse) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{16}
}

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_importer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{17}
}

type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_importer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{18}
}

var File_importer_proto protoreflect.FileDescriptor

const file_importer_proto_rawDesc = "" +
	"\n" +
	"\x0eimporter.proto\x12\bimporter\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x01\n" +
	"\aOptions\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\x12&\n" +
	"\x0emaxconcurrency\x18\x05 \x01(\x03R\x0emaxconcurrency\"\xc6\x01\n" +
	"\vInitRequest\x12+\n" +
	"\aoptions\x18\x01 \x01(\v2\x11.importer.OptionsR\aoptions\x12\x14\n" +
	"\x05proto\x18\x02 \x01(\tR\x05proto\x129\n" +
	"\x06config\x18\x03 \x03(\v2!.importer.InitRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"3\n" +
	"\fInitResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\r\n" +
	"\vInfoRequest\"N\n" +
	"\fInfoResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\tR\x06origin\x12\x12\n" +
	"\x04root\x18\x03 \x01(\tR\x04root\"\r\n" +
	"\vScanRequest\"\x91\x01\n" +
	"\fScanResponse\x12\x1a\n" +
	"\bpathname\x18\x01 \x01(\tR\bpathname\x12+\n" +
	"\x05error\x18\x03 \x01(\v2\x13.importer.ScanErrorH\x00R\x05error\x12.\n" +
	"\x06record\x18\x02 \x01(\v2\x14.importer.ScanRecordH\x00R\x06recordB\b\n" +
	"\x06result\"%\n" +
	"\tScanError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xc9\x01\n" +
	"\n" +
	"ScanRecord\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x128\n" +
	"\bfileinfo\x18\x02 \x01(\v2\x1c.importer.ScanRecordFileInfoR\bfileinfo\x12'\n" +
	"\x0ffile_attributes\x18\x03 \x01(\rR\x0efileAttributes\x126\n" +
	"\x05xattr\x18\x04 \x01(\v2\x1b.importer.ExtendedAttributeH\x00R\x05xattr\x88\x01\x01B\b\n" +
	"\x06_xattr\"\r\n" +
	"\vEOFResponse\"\\\n" +
	"\x11ExtendedAttribute\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.importer.ExtendedAttributeTypeR\x04type\"\xb5\x02\n" +
	"\x12ScanRecordFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x125\n" +
	"\bmod_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\amodTime\x12\x10\n" +
	"\x03dev\x18\x05 \x01(\x04R\x03dev\x12\x10\n" +
	"\x03ino\x18\x06 \x01(\x04R\x03ino\x12\x10\n" +
	"\x03uid\x18\a \x01(\x04R\x03uid\x12\x10\n" +
	"\x03gid\x18\b \x01(\x04R\x03gid\x12\x14\n" +
	"\x05nlink\x18\t \x01(\rR\x05nlink\x12\x1a\n" +
	"\busername\x18\n" +
	" \x01(\tR\busername\x12\x1c\n" +
	"\tgroupname\x18\v \x01(\tR\tgroupname\x12\x14\n" +
	"\x05flags\x18\f \x01(\rR\x05flags\";\n" +
	"\x11ScanResponseError\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"/\n" +
	"\x11OpenReaderRequest\x12\x1a\n" +
	"\bpathname\x18\x01 \x01(\tR\bpathname\"*\n" +
	"\x12OpenReaderResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"0\n" +
	"\x12CloseReaderRequest\x12\x1a\n" +
	"\bpathname\x18\x01 \x01(\tR\bpathname\"\x15\n" +
	"\x13CloseReaderResponse\"\x0e\n" +
	"\fCloseRequest\"\x0f\n" +
	"\rCloseResponse*\x87\x01\n" +
	"\x15ExtendedAttributeType\x12'\n" +
	"#EXTENDED_ATTRIBUTE_TYPE_UNSPECIFIED\x10\x00\x12$\n" +
	" EXTENDED_ATTRIBUTE_TYPE_EXTENDED\x10\x01\x12\x1f\n" +
	"\x1bEXTENDED_ATTRIBUTE_TYPE_ADS\x10\x022\x82\x03\n" +
	"\bImporter\x125\n" +
	"\x04Init\x12\x15.importer.InitRequest\x1a\x16.importer.InitResponse\x125\n" +
	"\x04Info\x12\x15.importer.InfoRequest\x1a\x16.importer.InfoResponse\x127\n" +
	"\x04Scan\x12\x15.importer.ScanRequest\x1a\x16.importer.ScanResponse0\x01\x12I\n" +
	"\n" +
	"OpenReader\x12\x1b.importer.OpenReaderRequest\x1a\x1c.importer.OpenReaderResponse0\x01\x12J\n" +
	"\vCloseReader\x12\x1c.importer.CloseReaderRequest\x1a\x1d.importer.CloseReaderResponse\x128\n" +
	"\x05Close\x12\x16.importer.CloseRequest\x1a\x17.importer.CloseResponseb\x06proto3"

var (
	file_importer_proto_rawDescOnce sync.Once
	file_importer_proto_rawDescData []byte
)

func file_importer_proto_rawDescGZIP() []byte {
	file_importer_proto_rawDescOnce.Do(func() {
		file_importer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_importer_proto_rawDesc), len(file_importer_proto_rawDesc)))
	})
	return file_importer_proto_rawDescData
}

var file_importer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_importer_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_importer_proto_goTypes = []any{
	(ExtendedAttributeType)(0),    // 0: importer.ExtendedAttributeType
	(*Options)(nil),               // 1: importer.Options
	(*InitRequest)(nil),           // 2: importer.InitRequest
	(*InitResponse)(nil),          // 3: importer.InitResponse
	(*InfoRequest)(nil),           // 4: importer.InfoRequest
	(*InfoResponse)(nil),          // 5: importer.InfoResponse
	(*ScanRequest)(nil),           // 6: importer.ScanRequest
	(*ScanResponse)(nil),          // 7: importer.ScanResponse
	(*ScanError)(nil),             // 8: importer.ScanError
	(*ScanRecord)(nil),            // 9: importer.ScanRecord
	(*EOFResponse)(nil),           // 10: importer.EOFResponse
	(*ExtendedAttribute)(nil),     // 11: importer.ExtendedAttribute
	(*ScanRecordFileInfo)(nil),    // 12: importer.ScanRecordFileInfo
	(*ScanResponseError)(nil),     // 13: importer.ScanResponseError
	(*OpenReaderRequest)(nil),     // 14: importer.OpenReaderRequest
	(*OpenReaderResponse)(nil),    // 15: importer.OpenReaderResponse
	(*CloseReaderRequest)(nil),    // 16: importer.CloseReaderRequest
	(*CloseReaderResponse)(nil),   // 17: importer.CloseReaderResponse
	(*CloseRequest)(nil),          // 18: importer.CloseRequest
	(*CloseResponse)(nil),         // 19: importer.CloseResponse
	nil,                           // 20: importer.InitRequest.ConfigEntry
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
}
var file_importer_proto_depIdxs = []int32{
	1,  // 0: importer.InitRequest.options:type_name -> importer.Options
	20, // 1: importer.InitRequest.config:type_name -> importer.InitRequest.ConfigEntry
	8,  // 2: importer.ScanResponse.error:type_name -> importer.ScanError
	9,  // 3: importer.ScanResponse.record:type_name -> importer.ScanRecord
	12, // 4: importer.ScanRecord.fileinfo:type_name -> importer.ScanRecordFileInfo
	11, // 5: importer.ScanRecord.xattr:type_name -> importer.ExtendedAttribute
	0,  // 6: importer.ExtendedAttribute.type:type_name -> importer.ExtendedAttributeType
	21, // 7: importer.ScanRecordFileInfo.mod_time:type_name -> google.protobuf.Timestamp
	2,  // 8: importer.Importer.Init:input_type -> importer.InitRequest
	4,  // 9: importer.Importer.Info:input_type -> importer.InfoRequest
	6,  // 10: importer.Importer.Scan:input_type -> importer.ScanRequest
	14, // 11: importer.Importer.OpenReader:input_type -> importer.OpenReaderRequest
	16, // 12: importer.Importer.CloseReader:input_type -> importer.CloseReaderRequest
	18, // 13: importer.Importer.Close:input_type -> importer.CloseRequest
	3,  // 14: importer.Importer.Init:output_type -> importer.InitResponse
	5,  // 15: importer.Importer.Info:output_type -> importer.InfoResponse
	7,  // 16: importer.Importer.Scan:output_type -> importer.ScanResponse
	15, // 17: importer.Importer.OpenReader:output_type -> importer.OpenReaderResponse
	17, // 18: importer.Importer.CloseReader:output_type -> importer.CloseReaderResponse
	19, // 19: importer.Importer.Close:output_type -> importer.CloseResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_importer_proto_init() }
func file_importer_proto_init() {
	if File_importer_proto != nil {
		return
	}
	file_importer_proto_msgTypes[2].OneofWrappers = []any{}
	file_importer_proto_msgTypes[6].OneofWrappers = []any{
		(*ScanResponse_Error)(nil),
		(*ScanResponse_Record)(nil),
	}
	file_importer_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_importer_proto_rawDesc), len(file_importer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_importer_proto_goTypes,
		DependencyIndexes: file_importer_proto_depIdxs,
		EnumInfos:         file_importer_proto_enumTypes,
		MessageInfos:      file_importer_proto_msgTypes,
	}.Build()
	File_importer_proto = out.File
	file_importer_proto_goTypes = nil
	file_importer_proto_depIdxs = nil
}
