.Dd July 8, 2025
.Dt PLAKAR-SERVICES 1
.Os
.Sh NAME
.Nm plakar-services
.Nd Manage optional Plakar-connected services
.Sh SYNOPSIS
.Nm plakar services status Ar service_name
.Nm plakar services enable Ar service_name
.Nm plakar services disable Ar service_name
.Sh DESCRIPTION
The
.Nm plakar services
command allows you to enable, disable, and inspect additional services that
integrate with the
.Nm plakar
platform via
.Xr plakar-login 1
authentication.
These services connect to the plakar.io infrastructure, and should only be
enabled if you agree to transmit non-sensitive operational data to plakar.io.
.Pp
All subcommands require prior authentication via
.Xr plakar-login 1 .
.Pp
At present, only the
.Dq alerting
service is available.
When enabled, alerting will:
.Bl -enum
.It
Send email notifications when operations fail.
.It
Expose the latest alerting reports in the Plakar UI
.Pq see Xr plakar-ui 1 .
.El
.Pp
By default, all services are disabled.
.Sh SUBCOMMANDS
.Bl -tag -width Ds
.It Ar status Ar service_name
Display the current configuration status (enabled or disabled) of the named
service.
Currently, only the "alerting" service is supported.
.It Ar enable Ar service_name
Enable the specified service.
Currently, only the "alerting" service is supported.
.It Ar disable Ar service_name
Disable the specified service.
Currently, only the "alerting" service is supported.
.El
.Sh EXAMPLES
Check the status of the alerting service:
.Bd -literal -offset indent
$ plakar services status alerting
.Ed
.Pp
Enable alerting:
.Bd -literal -offset indent
$ plakar services enable alerting
.Ed
.Pp
Disable alerting:
.Bd -literal -offset indent
$ plakar services disable alerting
.Ed
.Sh SEE ALSO
.Xr plakar-login 1 ,
.Xr plakar-ui 1