.Dd February 3, 2025
.Dt PLAKAR-DIGEST 1
.Os
.Sh NAME
.Nm plakar digest
.Nd Calculate digests for files in a Plakar snapshot
.Sh SYNOPSIS
.Nm
.Op Fl fast
.Ar snapshotID Ns No : Ns Ar filepath Op ...
.Sh DESCRIPTION
The
.Nm
command calculates and displays digests for specified
.Ar filepath
in a the given
.Ar snapshotID .
Multiple
.Ar snapshotID
and
.Ar filepath
may be given.
By default, the command computes the digest by reading the file
contents.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl fast
Return the pre-recorded digest for the file without re-computing it
from the file contents.
It's faster, but it does not verify the integrity against the current
contents.
.El
.Sh EXAMPLES
Calculate the digest of a file within a snapshot:
.Bd -literal -offset indent
$ plakar digest abc123:/etc/passwd
.Ed
.Pp
Retrieve the pre-recorded digest for faster output:
.Bd -literal -offset indent
$ plakar digest -fast abc123:/etc/netstart
.Ed
.Sh DIAGNOSTICS
.Ex -std
.Bl -tag -width Ds
.It 0
Command completed successfully.
.It >0
An error occurred, such as failure to retrieve a file digest or
invalid snapshot ID.
.El
.Sh SEE ALSO
.Xr plakar 1
